name: covid_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud_nsn: ^0.5.1
  lottie: ^2.6.0
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  font_awesome_flutter: ^10.8.0
  readmore: ^3.0.0
  pin_code_fields: ^8.0.1
  animated_text_kit: ^4.2.3
  math_expressions: ^2.6.0
  shared_preferences: ^2.5.2
  http: ^1.3.0
  async: ^2.11.0
  permission_handler: ^11.0.0
  image_picker: ^1.1.2
  pie_chart: ^5.4.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/virus.png
